feat: Update docs
AgoraIO/Agora-Flutter-SDK pull request #536
Opened 2021-12-21 08:53 UTC by littleGnAl

2021-12-24 07:46 UTC, yamasite requested changes

2021-12-24 07:46 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// This method needs to be called after the camera is started (for example, by calling startPreview or ).
这里应该是信息系统内部 key 解析的问题。先记录一下。

2021-12-24 07:46 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
这里应该不能有 return value

2021-12-24 07:46 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
void 没有 return value

2021-12-24 07:46 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
return value 不应该有

2021-12-24 07:46 UTC, yamasite commented on lib/src/rtc_engine.dart
>    Future<void> clearVideoWatermarks();
检查一下 void 函数的 return value

2021-12-24 08:45 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
是模板文件问题，已更新

2021-12-24 08:45 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
是模板文件问题，已更新

2021-12-24 08:45 UTC, yamasite commented on lib/src/rtc_engine.dart
> +  /// **return** 0: Success.
是模板文件问题，已更新

2021-12-24 08:45 UTC, yamasite commented on lib/src/rtc_engine.dart
>    Future<void> clearVideoWatermarks();
是模板文件问题，已更新

2021-12-24 09:10 UTC, littleGnAl commented
@yamasite Updated

2022-01-08 05:35 UTC, littleGnAl commented
Submit new PR

2022-01-08 05:35 UTC, closed without merging